//
// Created by ray on 3/21/24.
//

#ifndef GLOBAL_BODY_PLANNER_GLOBAL_BODY_REFERENCE_GENERATOR_H
#define GLOBAL_BODY_PLANNER_GLOBAL_BODY_REFERENCE_GENERATOR_H

#endif //GLOBAL_BODY_PLANNER_GLOBAL_BODY_REFERENCE_GENERATOR_H
